package org.twins.core.mappers.rest.twin;

import lombok.Getter;
import lombok.experimental.FieldNameConstants;
import org.twins.core.mappers.rest.MapperMode;
import org.twins.core.mappers.rest.MapperModeCollection;
import org.twins.core.mappers.rest.twinclass.TwinClassBaseRestDTOMapper;
import org.twins.core.mappers.rest.twinclass.TwinClassFieldRestDTOMapper;
import org.twins.core.mappers.rest.twinclass.TwinClassRestDTOMapper;

@Getter
@FieldNameConstants(onlyExplicitlyIncluded = true)
public enum RelationTwinMode implements MapperModeCollection {
    @FieldNameConstants.Include WHITE(0,
            TwinMode.HIDE,
            TwinMarkerMode.HIDE,
            TwinTagMode.HIDE,
            TwinRestDTOMapper.FieldsMode.NO_FIELDS,
            AttachmentMode.HIDE,
            TwinClassFieldRestDTOMapper.Mode.HIDE,
            TwinClassBaseRestDTOMapper.ClassMode.HIDE,
            TwinClassRestDTOMapper.StatusMode.HIDE,
            TwinClassRestDTOMapper.MarkerMode.HIDE,
            TwinClassRestDTOMapper.TagMode.HIDE,
            TwinLinkMode.HIDE,
            TwinLinkOnLinkMode.HIDE,
            MapperMode.TransitionMode.HIDE),
    @FieldNameConstants.Include GREEN(1,
            TwinMode.SHORT,
            MapperMode.TwinMarkerMode.HIDE,
            MapperMode.TwinTagMode.HIDE,
            TwinRestDTOMapper.FieldsMode.NO_FIELDS,
            AttachmentMode.HIDE,
            TwinClassFieldRestDTOMapper.Mode.HIDE,
            TwinClassBaseRestDTOMapper.ClassMode.SHORT,
            TwinClassRestDTOMapper.StatusMode.HIDE,
            TwinClassRestDTOMapper.MarkerMode.HIDE,
            TwinClassRestDTOMapper.TagMode.HIDE,
            TwinLinkMode.HIDE,
            TwinLinkOnLinkMode.HIDE,
            MapperMode.TransitionMode.HIDE),
    @FieldNameConstants.Include FOREST_GREEN(1,
            TwinMode.SHORT,
            MapperMode.TwinMarkerMode.HIDE,
            MapperMode.TwinTagMode.DETAILED,
            TwinRestDTOMapper.FieldsMode.NO_FIELDS,
            AttachmentMode.HIDE,
            TwinClassFieldRestDTOMapper.Mode.HIDE,
            TwinClassBaseRestDTOMapper.ClassMode.SHORT,
            TwinClassRestDTOMapper.StatusMode.HIDE,
            TwinClassRestDTOMapper.MarkerMode.HIDE,
            TwinClassRestDTOMapper.TagMode.HIDE,
            TwinLinkMode.HIDE,
            TwinLinkOnLinkMode.HIDE,
            MapperMode.TransitionMode.HIDE),
    @FieldNameConstants.Include YELLOW(2,
            TwinMode.DETAILED,
            MapperMode.TwinMarkerMode.HIDE,
            MapperMode.TwinTagMode.HIDE,
            TwinRestDTOMapper.FieldsMode.NO_FIELDS,
            AttachmentMode.HIDE,
            TwinClassFieldRestDTOMapper.Mode.HIDE,
            TwinClassBaseRestDTOMapper.ClassMode.SHORT,
            TwinClassRestDTOMapper.StatusMode.HIDE,
            TwinClassRestDTOMapper.MarkerMode.HIDE,
            TwinClassRestDTOMapper.TagMode.HIDE,
            TwinLinkMode.HIDE,
            TwinLinkOnLinkMode.HIDE,
            MapperMode.TransitionMode.HIDE),
    @FieldNameConstants.Include BLUE(3,
            TwinMode.DETAILED,
            MapperMode.TwinMarkerMode.HIDE,
            MapperMode.TwinTagMode.HIDE,
            TwinRestDTOMapper.FieldsMode.NOT_EMPTY_FIELDS,
            AttachmentMode.HIDE,
            TwinClassFieldRestDTOMapper.Mode.HIDE,
            TwinClassBaseRestDTOMapper.ClassMode.SHORT,
            TwinClassRestDTOMapper.StatusMode.HIDE,
            TwinClassRestDTOMapper.MarkerMode.HIDE,
            TwinClassRestDTOMapper.TagMode.HIDE,
            TwinLinkMode.HIDE,
            TwinLinkOnLinkMode.HIDE,
            MapperMode.TransitionMode.HIDE),
    @FieldNameConstants.Include BLACK(4,
            TwinMode.DETAILED,
            MapperMode.TwinMarkerMode.HIDE,
            MapperMode.TwinTagMode.HIDE,
            TwinRestDTOMapper.FieldsMode.NOT_EMPTY_FIELDS,
            AttachmentMode.HIDE,
            TwinClassFieldRestDTOMapper.Mode.HIDE,
            TwinClassBaseRestDTOMapper.ClassMode.DETAILED,
            TwinClassRestDTOMapper.StatusMode.HIDE,
            TwinClassRestDTOMapper.MarkerMode.HIDE,
            TwinClassRestDTOMapper.TagMode.HIDE,
            TwinLinkMode.HIDE,
            TwinLinkOnLinkMode.HIDE,
            MapperMode.TransitionMode.HIDE),
    @FieldNameConstants.Include GRAY(4,
            TwinMode.DETAILED,
            MapperMode.TwinMarkerMode.HIDE,
            MapperMode.TwinTagMode.DETAILED,
            TwinRestDTOMapper.FieldsMode.NOT_EMPTY_FIELDS,
            AttachmentMode.HIDE,
            TwinClassFieldRestDTOMapper.Mode.HIDE,
            TwinClassBaseRestDTOMapper.ClassMode.DETAILED,
            TwinClassRestDTOMapper.StatusMode.HIDE,
            TwinClassRestDTOMapper.MarkerMode.HIDE,
            TwinClassRestDTOMapper.TagMode.HIDE,
            TwinLinkMode.HIDE,
            TwinLinkOnLinkMode.HIDE,
            MapperMode.TransitionMode.HIDE),
    @FieldNameConstants.Include ORANGE(5,
            TwinMode.DETAILED,
            MapperMode.TwinMarkerMode.HIDE,
            MapperMode.TwinTagMode.HIDE,
            TwinRestDTOMapper.FieldsMode.NOT_EMPTY_FIELDS,
            AttachmentMode.HIDE,
            TwinClassFieldRestDTOMapper.Mode.DETAILED,
            TwinClassBaseRestDTOMapper.ClassMode.DETAILED,
            TwinClassRestDTOMapper.StatusMode.HIDE,
            TwinClassRestDTOMapper.MarkerMode.HIDE,
            TwinClassRestDTOMapper.TagMode.HIDE,
            TwinLinkMode.HIDE,
            TwinLinkOnLinkMode.HIDE,
            MapperMode.TransitionMode.HIDE);

    final int priority;
    final MapperMode[] configuredModes;

    RelationTwinMode(int priority, MapperMode... configuredModes) {
        this.priority = priority;
        this.configuredModes = configuredModes;
    }
}
