package org.twins.core.mappers.rest.twin;

import lombok.Getter;
import lombok.experimental.FieldNameConstants;
import org.twins.core.mappers.rest.MapperMode;
import org.twins.core.mappers.rest.MapperModeCollection;

@Getter
@FieldNameConstants(onlyExplicitlyIncluded = true)
public enum RelationTwinMode implements MapperModeCollection {
    @FieldNameConstants.Include WHITE(0,
            TwinMode.HIDE,
            TwinMarkerMode.HIDE,
            TwinTagMode.HIDE,
            TwinFieldCollectionMode.NO_FIELDS,
            AttachmentMode.HIDE,
            TwinClassFieldMode.HIDE,
            TwinClassMode.HIDE,
            TwinClassStatusMode.HIDE,
            TwinClassMarkerMode.HIDE,
            TwinClassTagMode.HIDE,
            TwinLinkMode.HIDE,
            TwinLinkOnLinkMode.HIDE,
            TransitionMode.HIDE),
    @FieldNameConstants.Include GREEN(1,
            TwinMode.SHORT,
            TwinMarkerMode.HIDE,
            TwinTagMode.HIDE,
            TwinFieldCollectionMode.NO_FIELDS,
            AttachmentMode.HIDE,
            TwinClassFieldMode.HIDE,
            TwinClassMode.SHORT,
            TwinClassStatusMode.HIDE,
            TwinClassMarkerMode.HIDE,
            TwinClassTagMode.HIDE,
            TwinLinkMode.HIDE,
            TwinLinkOnLinkMode.HIDE,
            TransitionMode.HIDE),
    @FieldNameConstants.Include FOREST_GREEN(1,
            TwinMode.SHORT,
            TwinMarkerMode.HIDE,
            TwinTagMode.DETAILED,
            TwinFieldCollectionMode.NO_FIELDS,
            AttachmentMode.HIDE,
            TwinClassFieldMode.HIDE,
            TwinClassMode.SHORT,
            TwinClassStatusMode.HIDE,
            TwinClassMarkerMode.HIDE,
            TwinClassTagMode.HIDE,
            TwinLinkMode.HIDE,
            TwinLinkOnLinkMode.HIDE,
            TransitionMode.HIDE),
    @FieldNameConstants.Include YELLOW(2,
            TwinMode.DETAILED,
            TwinMarkerMode.HIDE,
            TwinTagMode.HIDE,
            TwinFieldCollectionMode.NO_FIELDS,
            AttachmentMode.HIDE,
            TwinClassFieldMode.HIDE,
            TwinClassMode.SHORT,
            TwinClassStatusMode.HIDE,
            TwinClassMarkerMode.HIDE,
            TwinClassTagMode.HIDE,
            TwinLinkMode.HIDE,
            TwinLinkOnLinkMode.HIDE,
            TransitionMode.HIDE),
    @FieldNameConstants.Include BLUE(3,
            TwinMode.DETAILED,
            TwinMarkerMode.HIDE,
            TwinTagMode.HIDE,
            TwinFieldCollectionMode.NOT_EMPTY_FIELDS,
            AttachmentMode.HIDE,
            TwinClassFieldMode.HIDE,
            TwinClassMode.SHORT,
            TwinClassStatusMode.HIDE,
            TwinClassMarkerMode.HIDE,
            TwinClassTagMode.HIDE,
            TwinLinkMode.HIDE,
            TwinLinkOnLinkMode.HIDE,
            TransitionMode.HIDE),
    @FieldNameConstants.Include BLACK(4,
            TwinMode.DETAILED,
            TwinMarkerMode.HIDE,
            TwinTagMode.HIDE,
            TwinFieldCollectionMode.NOT_EMPTY_FIELDS,
            AttachmentMode.HIDE,
            TwinClassFieldMode.HIDE,
            TwinClassMode.DETAILED,
            TwinClassStatusMode.HIDE,
            TwinClassMarkerMode.HIDE,
            TwinClassTagMode.HIDE,
            TwinLinkMode.HIDE,
            TwinLinkOnLinkMode.HIDE,
            TransitionMode.HIDE),
    @FieldNameConstants.Include GRAY(4,
            TwinMode.DETAILED,
            TwinMarkerMode.HIDE,
            TwinTagMode.DETAILED,
            TwinFieldCollectionMode.NOT_EMPTY_FIELDS,
            AttachmentMode.HIDE,
            TwinClassFieldMode.HIDE,
            TwinClassMode.DETAILED,
            TwinClassStatusMode.HIDE,
            TwinClassMarkerMode.HIDE,
            TwinClassTagMode.HIDE,
            TwinLinkMode.HIDE,
            TwinLinkOnLinkMode.HIDE,
            TransitionMode.HIDE),
    @FieldNameConstants.Include ORANGE(5,
            TwinMode.DETAILED,
            TwinMarkerMode.HIDE,
            TwinTagMode.HIDE,
            TwinFieldCollectionMode.NOT_EMPTY_FIELDS,
            AttachmentMode.HIDE,
            TwinClassFieldMode.DETAILED,
            TwinClassMode.DETAILED,
            TwinClassStatusMode.HIDE,
            TwinClassMarkerMode.HIDE,
            TwinClassTagMode.HIDE,
            TwinLinkMode.HIDE,
            TwinLinkOnLinkMode.HIDE,
            TransitionMode.HIDE);

    final int priority;
    final MapperMode[] configuredModes;

    RelationTwinMode(int priority, MapperMode... configuredModes) {
        this.priority = priority;
        this.configuredModes = configuredModes;
    }
}
