CREATE OR REPLACE FUNCTION text2double(text) RETURNS DOUBLE PRECISION AS $$
BEGIN
    RETURN $1::DOUBLE PRECISION;
EXCEPTION WHEN others THEN
    RETURN NULL;
END;
$$ LANGUAGE plpgsql IMMUTABLE;


CREATE OR REPLACE FUNCTION text2timestamp(text)
    RETURNS TIMESTAMP WITHOUT TIME ZONE AS $$
BEGIN
    RETURN $1::TIMESTAMP WITHOUT TIME ZONE;
EXCEPTION WHEN others THEN
    RETURN NULL;
END;
$$ LANGUAGE plpgsql IMMUTABLE;
