-- System links (between system TwinClasses like TWINS_GLOSSARY → TWINS_GLOSSARY for see_also)
-- are global: they do not belong to any domain. The NOT NULL constraint on link.domain_id
-- prevented SystemEntityBootstrapService from persisting them.
--
-- twin_class.domain_id is already nullable for the same reason — this migration aligns link
-- with the same pattern.
ALTER TABLE link ALTER COLUMN domain_id DROP NOT NULL;

-- System data lists (e.g. GLOSSARY_CATEGORY) are global — they do not belong to any domain.
-- The NOT NULL constraint on data_list.domain_id prevented SystemEntityBootstrapService from
-- persisting them.
--
-- Same pattern as V1.4.300.01 (link.domain_id) and twin_class.domain_id (already nullable
-- since V1.3.98.01) — global system entities should not be forced into a domain.
ALTER TABLE data_list ALTER COLUMN domain_id DROP NOT NULL;


-- Renumber permission i18n UUIDs from random to deterministic range.
-- All existing permission i18n entries get UUIDs in
-- '00000000-0000-0000-0012-000000001000'..'.002000' range.
-- Generated by scripts/renumber_permission_i18n.py
--
-- Step 2 (insert missing i18n) and Step 3 (update permission refs) intentionally removed:
-- they duplicate SystemEntityBootstrapService.bootstrapSystemPermissions(), which creates
-- i18n + i18n_translation + permission rows with the correct deterministic UUIDs at startup.

-- Step 0: Add ON UPDATE CASCADE to permission i18n FKs.
-- V1.3.107.02 created these FKs without CASCADE (oversight — all other i18n FKs in the
-- project have it). Without CASCADE, the Step 1 renumber fails with FK violation because
-- permission.name_i18n_id / description_i18n_id still reference the old i18n.id values.
alter table permission
    drop constraint if exists permission_name_i18n_id_i18n_id_fk;

alter table permission
    add constraint permission_name_i18n_id_i18n_id_fk
        foreign key (name_i18n_id) references i18n on update cascade on delete no action;

alter table permission
    drop constraint if exists permission_description_i18n_id_i18n_id_fk;

alter table permission
    add constraint permission_description_i18n_id_i18n_id_fk
        foreign key (description_i18n_id) references i18n on update cascade on delete no action;

-- Step 1: Renumber existing i18n IDs. Permission rows are auto-updated via CASCADE.
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001006'::uuid WHERE id = 'fb8cd66e-db98-4882-9a4d-66cf78102290'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001007'::uuid WHERE id = 'a007e960-9b60-4e41-8d8c-5f1acd2a3bf4'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001012'::uuid WHERE id = '29d711a7-6cd2-4740-b81b-962a7fbbb72e'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001013'::uuid WHERE id = '8ee9e49d-9fe8-4024-8fc2-bf76a3a062be'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001016'::uuid WHERE id = 'a207a7b1-d16b-386a-83f5-cd0d9cffc048'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001017'::uuid WHERE id = 'ef4d65eb-594d-3b17-b5d3-66ab79956748'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-00000000101a'::uuid WHERE id = 'a207a7b1-d16b-386a-83f5-cd0d9cffc049'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-00000000101b'::uuid WHERE id = 'ef4d65eb-594d-3b17-b5d3-66ab79956749'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-00000000101c'::uuid WHERE id = 'a207a7b1-d16b-386a-83f5-cd0d9cffc050'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-00000000101d'::uuid WHERE id = 'ef4d65eb-594d-3b17-b5d3-66ab79956750'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-00000000102a'::uuid WHERE id = 'a207a7b1-d16b-386a-83f5-cd0d9cffc051'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-00000000102b'::uuid WHERE id = 'ef4d65eb-594d-3b17-b5d3-66ab79956751'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-00000000102c'::uuid WHERE id = 'a207a7b1-d16b-386a-83f5-cd0d9cffc052'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-00000000102d'::uuid WHERE id = 'ef4d65eb-594d-3b17-b5d3-66ab79956752'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-00000000102e'::uuid WHERE id = 'a207a7b1-d16b-386a-83f5-cd0d9cffc053'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-00000000102f'::uuid WHERE id = 'ef4d65eb-594d-3b17-b5d3-66ab79956753'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001030'::uuid WHERE id = 'a207a7b1-d16b-386a-83f5-cd0d9cffc054'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001031'::uuid WHERE id = 'ef4d65eb-594d-3b17-b5d3-66ab79956754'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001034'::uuid WHERE id = 'a207a7b1-d16b-386a-83f5-cd0d9cffc006'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001035'::uuid WHERE id = 'ef4d65eb-594d-3b17-b5d3-66ab79956706'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001038'::uuid WHERE id = 'a207a7b1-d16b-386a-83f5-cd0d9cffc007'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001039'::uuid WHERE id = 'ef4d65eb-594d-3b17-b5d3-66ab79956707'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-00000000103a'::uuid WHERE id = 'a207a7b1-d16b-386a-83f5-cd0d9cffc008'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-00000000103b'::uuid WHERE id = 'ef4d65eb-594d-3b17-b5d3-66ab79956708'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001044'::uuid WHERE id = 'a207a7b1-d16b-386a-83f5-cd0d9cffc002'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001045'::uuid WHERE id = 'ef4d65eb-594d-3b17-b5d3-66ab79956702'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001054'::uuid WHERE id = 'f1203df7-a6d9-4b5d-a3ab-75481afe9877'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001055'::uuid WHERE id = 'eebf50d3-3053-42ea-9863-57104ce9b7fe'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001060'::uuid WHERE id = 'b9ebdb43-e334-46f2-93d8-d8d79d66c6a6'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001061'::uuid WHERE id = 'edf24088-797d-4485-98af-929710bc046c'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001062'::uuid WHERE id = '232cbe43-9ca5-427a-86c9-74a56c8b8e7f'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001063'::uuid WHERE id = '782a73d2-5eff-43db-982e-943fd1f72426'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-00000000106c'::uuid WHERE id = '9d9a97b8-ae09-467b-ad09-4a12ae89abb8'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-00000000106d'::uuid WHERE id = '110a1ef2-be50-4d74-b68b-9a2d28b1b83f'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001076'::uuid WHERE id = '19aa7ccf-cbec-4922-80a2-1b5ca00dd3b8'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001077'::uuid WHERE id = 'ef4d65eb-594d-3b17-b5d3-66ab79956725'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001078'::uuid WHERE id = '1b30d251-b068-4bb8-aaa2-21382feb7d56'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001079'::uuid WHERE id = '792a5685-751b-496c-b1ef-322d96e1c94a'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001082'::uuid WHERE id = '6b066663-6182-4632-ab63-b53c27d00651'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001083'::uuid WHERE id = 'a585f023-595f-4c53-bb49-a23b48a731fd'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-00000000108e'::uuid WHERE id = 'a35b40b9-65bf-4a72-aec4-a5c62cae5e3e'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-00000000108f'::uuid WHERE id = 'f27a3375-7742-466b-acf3-1581a5dec66f'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001098'::uuid WHERE id = '49dfc3a4-4dc7-4769-8463-0b05f4a17b2d'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001099'::uuid WHERE id = 'fdc14ecd-bf6a-48bc-a570-caa1088d7b65'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-0000000010a2'::uuid WHERE id = '89806276-a5d1-4bf5-9e29-d2387bf6cfd8'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-0000000010a3'::uuid WHERE id = 'c118e27b-b756-43a4-b722-66ea2443d68d'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-0000000010ac'::uuid WHERE id = '31b339c3-f8f5-4474-b2d4-8adf752f916d'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-0000000010ad'::uuid WHERE id = 'a781f6da-184e-425e-a582-7194dbbb651a'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-0000000010b6'::uuid WHERE id = '4a59d325-5218-4aa1-959e-e406a46f8e51'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-0000000010b7'::uuid WHERE id = '5cf2fe15-8958-4be0-87f9-a37816b853b3'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-0000000010c0'::uuid WHERE id = 'e3833ff4-e5b2-410d-a48a-1aaada9c681c'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-0000000010c1'::uuid WHERE id = '5019537b-27a9-4603-8671-2abfcc9be1cf'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-0000000010fc'::uuid WHERE id = '1751502c-8da7-4b32-8101-62df0f9ad11e'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-0000000010fd'::uuid WHERE id = '22626457-54f4-4927-9d05-ee8cb13b237c'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-0000000010fe'::uuid WHERE id = 'b407a7b1-d16b-386a-83f5-cd0d9cffc555'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-0000000010ff'::uuid WHERE id = 'cf4d65eb-594d-3b17-b5d3-66ab79956756'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001102'::uuid WHERE id = 'd507a7b1-d16b-386a-83f5-cd0d9cffc557'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001103'::uuid WHERE id = 'df4d65eb-594d-3b17-b5d3-66ab79956758'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001104'::uuid WHERE id = 'e607a7b1-d16b-386a-83f5-cd0d9cffc559'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001105'::uuid WHERE id = 'ef4d65eb-594d-3b17-b5d3-66ab79956760'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001106'::uuid WHERE id = 'cdc74f7c-2894-4b01-a981-e6441d0aacaf'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001107'::uuid WHERE id = '41689330-3a80-48a3-870e-2ae48237eea9'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001108'::uuid WHERE id = '8e44d042-3532-4ccf-b4e9-efad657f176e'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001109'::uuid WHERE id = '3578b14d-8e30-4b25-9e56-d7a5486d9a51'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-00000000110c'::uuid WHERE id = '4ea7f1d1-167d-43a5-8a25-5ca41138e09d'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-00000000110d'::uuid WHERE id = '7a7a93a6-7b1a-4f52-b6d6-9ec07a6766d4'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-00000000110e'::uuid WHERE id = 'f53d63a9-4b8b-41a0-8a63-0b8afcfd17ca'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-00000000110f'::uuid WHERE id = 'c2c4b5e7-12a0-4f7b-97c1-3d03fbb0a65f'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001110'::uuid WHERE id = '07e9a2b8-9f44-4379-bb23-6a687d5c70f4'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001111'::uuid WHERE id = '3db87e6a-10cb-4d1f-b1b6-5b69d41e3459'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001112'::uuid WHERE id = 'f1b73647-b7d6-4d10-9d5b-086a4e8f4e68'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001113'::uuid WHERE id = '7f48e22b-1205-4b44-8c48-9edb0a479c3d'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001116'::uuid WHERE id = '82c8b983-f135-4a18-8a40-7a4b02442099'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001117'::uuid WHERE id = '2906c5c0-49bc-4639-9ad6-004dbdf3d263'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001118'::uuid WHERE id = '1f6c60f6-b1c0-4db1-9d9b-60b6f6716a0c'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001119'::uuid WHERE id = '1aa03e1e-274e-4b94-91d6-5701efb3d3e1'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001124'::uuid WHERE id = 'bfcaf5aa-2c7e-49f1-bb71-72bddb8a0abf'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001125'::uuid WHERE id = '9ab910b0-6054-4412-a034-c00c1e136414'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-00000000112e'::uuid WHERE id = '1d03aee8-a358-48b0-9a77-b7cffeb6afe0'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-00000000112f'::uuid WHERE id = 'ba202321-5091-4da0-95b0-8fc6fcc0110a'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001138'::uuid WHERE id = 'aaebc4a6-92a3-4f66-8394-9824ecda27ea'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001139'::uuid WHERE id = 'e0e27b29-abb9-4e80-ad3f-cca9b3819fdc'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001142'::uuid WHERE id = '1f752658-3594-4b35-8311-76aa11d21468'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001143'::uuid WHERE id = 'd639ec60-a9c3-4584-8572-b22538f3c189'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001144'::uuid WHERE id = '2d35015c-2446-4339-8cad-b60b9dbac6c8'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001145'::uuid WHERE id = '9e4026c0-1496-4fae-aa83-e2a973f91bc0'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-00000000114e'::uuid WHERE id = 'bb4e4298-469b-4cb7-baa2-a5e1932709a4'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-00000000114f'::uuid WHERE id = '123e3aae-5b83-4e61-8e1f-e5b4ec602d60'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001158'::uuid WHERE id = '6bec0d9e-646e-4de3-8527-8d43af615a71'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001159'::uuid WHERE id = 'c0275859-5465-40eb-96c9-47e56f23ecbd'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001162'::uuid WHERE id = 'e29fb86a-1780-4751-9799-0ec72bc6c923'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001163'::uuid WHERE id = 'e7f363b9-2f3e-453c-8fd9-dc29c0aa683c'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001164'::uuid WHERE id = '7856222c-7e24-4f7d-9962-7ae67a7b05e1'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001165'::uuid WHERE id = 'c3d0bbf2-eb05-4515-ab45-2ecf5e21c993'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001166'::uuid WHERE id = '185565a6-9727-4d08-b26d-eff24bf3b248'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001167'::uuid WHERE id = '54cf7275-615e-4608-8e63-d48c175d43a9'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001168'::uuid WHERE id = '66d51f57-78f7-4eca-aa01-fabcc048e327'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001169'::uuid WHERE id = '12d871d2-5c23-4b23-a139-a85e3e798f1f'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-00000000116a'::uuid WHERE id = 'f01254bf-89a2-4e52-9e85-1205aa69bd29'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-00000000116b'::uuid WHERE id = 'c6fb326f-d2a5-4021-b22d-29cf1fa45204'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001182'::uuid WHERE id = '2c4ec981-4e53-4968-9ffe-215e69cee856'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001183'::uuid WHERE id = '9b688865-81be-4ff1-9ea6-3e0d5f88ed01'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-00000000118e'::uuid WHERE id = 'a207a7b1-d16b-386a-83f5-cd0d9cffc039'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-00000000118f'::uuid WHERE id = 'ef4d65eb-594d-3b17-b5d3-66ab79956739'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001192'::uuid WHERE id = 'a207a7b1-d16b-386a-83f5-cd0d9cffc040'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001193'::uuid WHERE id = 'ef4d65eb-594d-3b17-b5d3-66ab79956740'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001194'::uuid WHERE id = 'a207a7b1-d16b-386a-83f5-cd0d9cffc041'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001195'::uuid WHERE id = 'ef4d65eb-594d-3b17-b5d3-66ab79956741'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001196'::uuid WHERE id = '7f7175c8-6d23-48b3-9bd2-2277ccf03f95'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001197'::uuid WHERE id = 'f3c8d5cd-1c08-4e29-bc09-df293e1ab44b'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001198'::uuid WHERE id = 'a207a7b1-d16b-386a-83f5-cd0d9cffc042'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-000000001199'::uuid WHERE id = 'ef4d65eb-594d-3b17-b5d3-66ab79956742'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-00000000119c'::uuid WHERE id = 'a207a7b1-d16b-386a-83f5-cd0d9cffc043'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-00000000119d'::uuid WHERE id = 'ef4d65eb-594d-3b17-b5d3-66ab79956743'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-00000000119e'::uuid WHERE id = 'a207a7b1-d16b-386a-83f5-cd0d9cffc044'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-00000000119f'::uuid WHERE id = 'ef4d65eb-594d-3b17-b5d3-66ab79956744'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-0000000011a0'::uuid WHERE id = 'b871973e-2f36-483e-a899-6ab754a2739c'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-0000000011a1'::uuid WHERE id = '88eafed6-b864-45ff-bc99-0485dd8ac06c'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-0000000011ac'::uuid WHERE id = 'a207a7b1-d16b-386a-83f5-cd0d9cffc045'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-0000000011ad'::uuid WHERE id = 'ef4d65eb-594d-3b17-b5d3-66ab79956745'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-0000000011b0'::uuid WHERE id = 'a207a7b1-d16b-386a-83f5-cd0d9cffc046'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-0000000011b1'::uuid WHERE id = 'ef4d65eb-594d-3b17-b5d3-66ab79956746'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-0000000011b2'::uuid WHERE id = 'a207a7b1-d16b-386a-83f5-cd0d9cffc047'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-0000000011b3'::uuid WHERE id = 'ef4d65eb-594d-3b17-b5d3-66ab79956747'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-0000000011b4'::uuid WHERE id = '4bca9177-8301-42dd-b947-bf93d1d75c8a'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-0000000011b5'::uuid WHERE id = '006df45e-bcf8-4aa8-8776-4decb7c6f537'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-0000000011be'::uuid WHERE id = 'dbce948e-47a3-4e5b-a6ec-8c6e2a06f6f0'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-0000000011bf'::uuid WHERE id = 'e9638f97-9dbf-4c07-a871-f5c57df87f69'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-0000000011c0'::uuid WHERE id = '2e9a1c12-4a3b-4e02-9c28-21f241377d33'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-0000000011c1'::uuid WHERE id = '11d9c5b4-153e-4e57-99e6-35d5401c45a3'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-0000000011c2'::uuid WHERE id = 'b18a2c65-b9d6-4e4d-8c5a-f1e0688a11bc'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-0000000011c3'::uuid WHERE id = '96f06362-94ad-4c9f-b476-53e65a9470bc'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-0000000011c4'::uuid WHERE id = 'd1a1799c-7984-4889-b3e7-34803f3c7ca0'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-0000000011c5'::uuid WHERE id = 'fbd8d3db-9c85-4dbd-80ea-44fa3e4e1ee7'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-0000000011c6'::uuid WHERE id = '0b3c53e9-3a3e-48b6-81de-cfcd3ccf0f23'::uuid;
UPDATE i18n SET id = '00000000-0000-0000-0012-0000000011c7'::uuid WHERE id = '6a785344-0f28-4f5c-8ee8-eaf646efb6d9'::uuid;
