-- Rename history_notification_schema_map to history_notification
ALTER TABLE history_notification_schema_map RENAME TO history_notification;

-- Rename primary key constraint
ALTER TABLE history_notification RENAME CONSTRAINT history_notification_schema_map_pk TO history_notification_pk;

-- Rename foreign key constraints
ALTER TABLE history_notification RENAME CONSTRAINT history_notification_schema_map_twin_class_id_id_fk TO history_notification_twin_class_id_fk;
ALTER TABLE history_notification RENAME CONSTRAINT history_notification_schema_map_twin_class_field_id_fk TO history_notification_twin_class_field_id_fk;
ALTER TABLE history_notification RENAME CONSTRAINT history_notification_schema_map_history_type_id_fk TO history_notification_history_type_id_fk;
ALTER TABLE history_notification RENAME CONSTRAINT history_notification_schema_map_notification_schema_id_fk TO history_notification_notification_schema_id_fk;
ALTER TABLE history_notification RENAME CONSTRAINT history_notification_schema_map_recipient_id_fk TO history_notification_recipient_id_fk;
ALTER TABLE history_notification RENAME CONSTRAINT history_notification_schema_map_channel_event_id_fk TO history_notification_notification_channel_event_id_fk;
ALTER TABLE history_notification RENAME CONSTRAINT history_notification_schema_map_twin_validator_set_id_fk TO history_notification_twin_validator_set_id_fk;

-- Rename unique constraint
ALTER TABLE history_notification RENAME CONSTRAINT history_notification_schema_map_uq TO history_notification_uq;
