package org.twins.core.enums.draft;

import lombok.Getter;

@Getter
public enum DraftStatus {
    UNDER_CONSTRUCTION,
    CONSTRUCTION_EXCEPTION,
    ERASE_SCOPE_COLLECT_PLANNED,
    ERASE_SCOPE_COLLECT_NEED_START,
    ERASE_SCOPE_COLLECT_IN_PROGRESS,
    ERASE_SCOPE_COLLECT_EXCEPTION,
    NORMALIZE_EXCEPTION,
    CHECK_CONFLICTS_EXCEPTION,
    UNCOMMITED,
    COMMIT_NEED_START,
    COMMIT_IN_PROGRESS,
    COMMIT_EXCEPTION,
    LOCKED,
    OUT_OF_DATE,
    COMMITED;
}
