server.port=8080

logging.level.org.apache.http=DEBUG
logging.level.httpclient.wire=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.io.springfox=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.main.allow-circular-references=true
spring.main.lazy-initialization=true

spring.datasource.url=jdbc:postgresql://192.168.7.209:5432/twins
spring.datasource.username=gateway80lvl
spring.datasource.password=TVlk8z4e708PHsIz
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=10
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.show-sql=true

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.tagsSorter=alpha

spring.flyway.enabled=false
spring.flyway.placeholder-replacement=false
spring.jackson.default-property-inclusion = NON_NULL
cambium.i18n.defaultLocale=en

draft.erase.scope.collect.scheduler.delay=500

app.cache.auth-token.initial-capacity=1000
app.cache.auth-token.max-size=10000
app.cache.auth-token.max-ttl=10m
app.cache.auth-token.clock-skew=5s
app.cache.user-permissions.initial-capacity=1000
app.cache.user-permissions.max-size=10000
app.cache.user-permissions.ttl=1m

api.unsecured.enable=true
twins.system-entity.bootstrap.enabled=true
